name: Task generator 

on: create

jobs:
  log-github-event-goodies:
    name: "Provide task randomly"
    runs-on: ubuntu-latest
    steps:
        # Checkout repository
      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Run generation script
        env:
          MESSAGE: ${{github.event.head_commit.message}}
          USER: ${{github.event.pusher.name}}
        run: |
          python3 .github/workflows/InitiallySelectTask.py
          
      - name: Commit files
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add README.md
             git add ./.content/task.log
             git status
             git commit -m "Replace Task" || echo "Task unchanged"
             
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: main
