name: Task generator 

on: push

jobs:
  log-github-event-goodies:
    name: "Provide task randomly"
    runs-on: ubuntu-latest
    steps:
        # Checkout repository
      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Logging
        env:
          MESSAGE: ${{github.event.head_commit.message}}
          USER: ${{github.event.pusher.name}}
        run: |
          python3 .github/workflows/InitiallySelectTask.py
          
