name: CI

on: [push, fork]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2

      - name: Run extraction
        run: |
             python ./TaskGenerator/RandomlySelectTask.py
             
      - name: Commit files
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add README.md
             git status
             git commit -m "Replace Task" || echo "Task unchanged"
             
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: main
