name: Task generator 

on: push

jobs:
  log-github-event-goodies:
    name: "Provide task randomly"
    runs-on: ubuntu-latest
    env:
      TASKFILE: 'not defined'
    steps:
        # Checkout repository
      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Run generation script
        env:
          MESSAGE: ${{github.event.head_commit.message}}
          USER: ${{github.event.pusher.name}}
        run: |
             python3 .github/workflows/InitiallySelectTask.py
             echo "------------------"
             echo "$TASK"
             echo "TASKFILE=echo {{$TASK}}" >> $GITHUB_ENV
             echo "$TASKFILE"
          
      - name: Commit files
        run: |
             echo "$TASKFILE"
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add README.md
             git status
             git commit -m "Replace Task - $TASK" || echo "Task unchanged"
             
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: main
